[package]
name = "ledgerscope-web-api"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "web-api"
path = "src/main.rs"

[dependencies]
ledgerscope-domain.workspace = true
ledgerscope-application.workspace = true
ledgerscope-adapters.workspace = true

anyhow.workspace = true
bon.workspace = true
tokio.workspace = true
tracing.workspace = true
reqwest.workspace = true
hex.workspace = true

axum.workspace = true
serde.workspace = true
tracing-subscriber.workspace = true
